import type { SessionState } from '../api/redmist/session-state';
import type { SessionStatePatch } from '../api/redmist/session-state-patch';
import type { CarPosition } from '../api/redmist/car-position';
import type { CarPositionPatch } from '../api/redmist/car-position-patch';
import { Flags } from '../api/redmist/flags';

// Red Mist V2 patches are "nullable-field" objects (generated by the server's
// PatchClassGenerator): every property mirrors the base model and null means
// "no change". Merging is therefore a shallow copy of all non-null fields.
// See RedMist.Timing.UI LiveTimingViewModel for the reference implementation.

/**
 * Merge a SessionStatePatch into a SessionState. `carPositions` is
 * intentionally excluded — car updates are applied through the car map so lap
 * accumulation and pruning stay in one place (see sessionStore).
 */
export function mergeSessionPatch(base: SessionState, patch: SessionStatePatch): SessionState {
  const out: Record<string, unknown> = { ...base };
  for (const [key, value] of Object.entries(patch)) {
    if (key === 'carPositions') continue;
    if (value !== null && value !== undefined) out[key] = value;
  }
  return out as unknown as SessionState;
}

export function mergeCarPatch(base: CarPosition, patch: CarPositionPatch): CarPosition {
  const out: Record<string, unknown> = { ...base };
  for (const [key, value] of Object.entries(patch)) {
    if (value !== null && value !== undefined) out[key] = value;
  }
  return out as unknown as CarPosition;
}

export function emptyCarPosition(number: string): CarPosition {
  return {
    invalidPosition: -999,
    eventId: '',
    sessionId: '',
    number,
    transponderId: 0,
    class: '',
    bestTime: '',
    bestLap: 0,
    isBestTime: false,
    isBestTimeClass: false,
    inClassGap: '',
    inClassDifference: '',
    overallGap: '',
    overallDifference: '',
    totalTime: '',
    lastLapTime: '',
    lastLapCompleted: 0,
    pitStopCount: null,
    lastLapPitted: null,
    lapsLedOverall: null,
    lapsLedInClass: null,
    overallPosition: 0,
    classPosition: 0,
    overallStartingPosition: 0,
    overallPositionsGained: -999,
    inClassStartingPosition: 0,
    inClassPositionsGained: -999,
    isOverallMostPositionsGained: false,
    isClassMostPositionsGained: false,
    penalityLaps: 0,
    penalityWarnings: 0,
    blackFlags: 0,
    isEnteredPit: false,
    isPitStartFinish: false,
    isExitedPit: false,
    isInPit: false,
    lapIncludedPit: false,
    lastLoopName: '',
    isStale: false,
    trackFlag: Flags.Unknown,
    localFlag: Flags.Unknown,
    lapHadLocalFlag: null,
    completedSections: [],
    projectedLapTimeMs: 0,
    lapStartTime: '',
    driverName: '',
    driverId: '',
    inCarVideo: null,
    latitude: null,
    longitude: null,
    currentStatus: '',
    impactWarning: false,
    inClassFastestAveragePace: false,
    trackTempDegF: null,
    trackPrecipitationPerc: null,
  };
}

export function emptySessionState(): SessionState {
  return {
    eventId: 0,
    eventName: '',
    sessionId: 0,
    sessionName: '',
    lapsToGo: 0,
    timeToGo: '',
    localTimeOfDay: '',
    runningRaceTime: '',
    isPracticeQualifying: false,
    sessionStartTime: new Date(0),
    sessionEndTime: null,
    localTimeZoneOffset: 0,
    isLive: false,
    eventEntries: [],
    carPositions: [],
    currentFlag: Flags.Unknown,
    flagDurations: [],
    greenTimeMs: null,
    greenLaps: null,
    yellowTimeMs: null,
    yellowLaps: null,
    numberOfYellows: null,
    redTimeMs: null,
    averageRaceSpeed: null,
    leadChanges: null,
    sections: [],
    classColors: {},
    announcements: [],
    lastUpdated: null,
    classOrder: {},
    isSimulation: false,
    isArchived: false,
    trackTempDegF: null,
    trackPrecipitationPerc: null,
  };
}

/** Convert a full CarPosition (e.g. from REST snapshot) into a patch shape. */
export function carPositionToPatch(car: CarPosition): CarPositionPatch {
  // Field names are identical between CarPosition and CarPositionPatch; the
  // patch type just makes everything nullable.
  return { ...(car as unknown as CarPositionPatch) };
}
